[tool.mypy]
    disallow_incomplete_defs = true
    disallow_untyped_defs    = true
    ignore_missing_imports   = true
    python_version           = "3.13"
    warn_no_return           = true
    warn_return_any          = true

[tool.ruff]
    line-length = 120
    target-version = "py313"

[tool.ruff.format]
    quote-style = "double"
    indent-style = "space"
    docstring-code-format = true

[tool.yamlfix]
    whitelines = 1
    section_whitelines = 1
    sequence_style = "keep_style"
    explicit_start = false
